db:
  image: postgres
  environment:
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: postgres
web:
  image: 5916a543e9bf
  links:
   - db
  ports:
   - "8888:8888"
  volumes:
    - ./config:/etc/kinto